# Generated by Django 3.2.14 on 2022-09-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='OrientacaoSexual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='OrigemEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Passo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('matricula', models.CharField(blank=True, max_length=30, null=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('data_criacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de criação')),
                ('renda_per_capita', models.FloatField(blank=True, null=True, verbose_name='Renda per capita')),
                ('cotista', models.BooleanField(default=False, verbose_name='É cotista')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('regiao_moradia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Região de moradia')),
                ('quantidade_filhos', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de filhos entre 0 e 6 anos')),
                ('quantidade_pessoas_familia', models.IntegerField(blank=True, null=True, verbose_name='Quantas pessoas compõem o núcleo familiar')),
                ('quantidade_materias_periodo', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de matérias no período')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('beneficiario_bolsa_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.beneficiario', verbose_name='Beneficiário')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.curso', verbose_name='Curso')),
                ('orientacao_sexual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.orientacaosexual', verbose_name='Orientação sexual')),
                ('origem_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.origemescolar', verbose_name='Origem escolar')),
                ('passo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.passo', verbose_name='Passo')),
                ('raca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.raca', verbose_name='Raça')),
            ],
        ),
    ]
