# Generated by Django 3.2.14 on 2022-09-24 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20220923_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Ano')),
                ('periodo', models.IntegerField(max_length=2, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Período')),
            ],
            options={
                'unique_together': {('ano', 'periodo')},
            },
        ),
    ]
