# Generated by Django 3.2.14 on 2022-09-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_edital'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='edital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aluno.edital', verbose_name='Edital'),
            preserve_default=False,
        ),
    ]
