# Generated by Django 3.2.14 on 2022-07-21 22:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campi',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadSheet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('edital', models.CharField(blank=True, max_length=200, null=True, verbose_name='Edital')),
                ('ano', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
                ('campi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spreadsheet.campi', verbose_name='Campi')),
            ],
        ),
    ]
