# Generated by Django 3.2.14 on 2022-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, choices=[(0, 'Barreiros'), (1, 'Vitória de Santo Antão'), (2, 'Belo Jardim')], max_length=50, null=True, verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[(0, 'Usuário'), (1, 'Administrador')], default=0, max_length=50, verbose_name='Permissão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sobrenome'),
        ),
    ]
