# Generated by Django 3.2.14 on 2022-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220918_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, choices=[('0', 'Barreiros'), ('1', 'Vitória de Santo Antão'), ('2', 'Belo Jardim')], max_length=50, null=True, verbose_name='Campus'),
        ),
    ]
