# Generated by Django 3.2.14 on 2022-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, choices=[('0', 'Barreiros'), ('1', 'Belo Jardim'), ('2', 'Vitória de Santo Antão')], max_length=50, null=True, verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('0', 'Usuário'), ('1', 'Administrador')], default=0, max_length=50, verbose_name='Permissão'),
        ),
    ]
